/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: NuiBSL4ZhHH+KDxkQL8LqsKuUkl/ZoUIEUClMMk0lTndUXcOSmcT+juSBJ/DQ4mlSDOl3w/SKqZQpV9iVsRTIw==
 */

// eslint:disable
// tslint:disable

interface Eliminationandexchange {
	abdominal: string | null;
	bowelsounds: string | null;
	defecationpattern: string | null;
	id: number;
	palpation: string | null;
	patient_id: number;
	percussion: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	type_ofofincontinence: string | null;
	urinarypattern: string | null;
}
export default Eliminationandexchange;

interface Eliminationandexchange_InsertParameters {
	abdominal?: string | null;
	bowelsounds?: string | null;
	defecationpattern?: string | null;
	id: number;
	palpation?: string | null;
	patient_id: number;
	percussion?: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	type_ofofincontinence?: string | null;
	urinarypattern?: string | null;
}
export type { Eliminationandexchange_InsertParameters };
