/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: +R3RjpQd14inMFdnvGaeFguJ1q4CKMBtyUJLbatqTelqN6SDyVA0D6UuStNo6nCu7kVbpn8HsbSClEW+T6MCdw==
 */

// eslint:disable
// tslint:disable

interface Healthpromotion {
	allergies: string | null;
	amountofdailyuse: string | null;
	dailyexercise: string | null;
	dietregime: string | null;
	diseaseshistory: string | null;
	drughistory: string | null;
	drugs: string | null;
	id: number;
	medicalregime: string | null;
	patient_id: number;
	redactionalactivity: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	riskfactorprogression: string | null;
	stressindailylife: string | null;
}
export default Healthpromotion;

interface Healthpromotion_InsertParameters {
	allergies?: string | null;
	amountofdailyuse?: string | null;
	dailyexercise?: string | null;
	dietregime?: string | null;
	diseaseshistory?: string | null;
	drughistory?: string | null;
	drugs?: string | null;
	id: number;
	medicalregime?: string | null;
	patient_id: number;
	redactionalactivity?: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	riskfactorprogression?: string | null;
	stressindailylife?: string | null;
}
export type { Healthpromotion_InsertParameters };
