/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xdZCT3dTRD6nasf/WJizKzRu7RlmYbb0/qyHkX41IvAbgnaPQGjrrxt9IWQNvCW9qI/zIfd3Bgu5vLhZeARHqg==
 */

// eslint:disable
// tslint:disable

import Patient, { Patient_InsertParameters } from './patient';

interface DatabaseSchema {
	patient: { record: Patient; insert: Patient_InsertParameters };
}
export default DatabaseSchema;

function serializeValue(
	_tableName: string,
	_columnName: string,
	value: unknown,
): unknown {
	return value;
}
export { serializeValue };
