/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: yY2S++BtQUiQB4UrD7Nx9woN2BbyAuRq20Pcxm/UpVT7E0DQgFNlDHLG3yTprdKQzbUWQtuKWq8gWf13/ZZhEw==
 */

// eslint:disable
// tslint:disable

import Eliminationandexchange, {
	Eliminationandexchange_InsertParameters,
} from './eliminationandexchange';
import Healthpromotion, {
	Healthpromotion_InsertParameters,
} from './healthpromotion';
import Nutrition, { Nutrition_InsertParameters } from './nutrition';
import Patient, { Patient_InsertParameters } from './patient';

interface DatabaseSchema {
	eliminationandexchange: {
		record: Eliminationandexchange;
		insert: Eliminationandexchange_InsertParameters;
	};
	healthpromotion: {
		record: Healthpromotion;
		insert: Healthpromotion_InsertParameters;
	};
	nutrition: { record: Nutrition; insert: Nutrition_InsertParameters };
	patient: { record: Patient; insert: Patient_InsertParameters };
}
export default DatabaseSchema;

function serializeValue(
	_tableName: string,
	_columnName: string,
	value: unknown,
): unknown {
	return value;
}
export { serializeValue };
