/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: p2SfJ17zKbkWiu69mugfKsmXtkI33eHp+kssrr+8zRzsON8ceYaXqZNSw5cYr1hgy5floPfACN7FkFWS6G38KQ==
 */

// eslint:disable
// tslint:disable

import Cardiovascularstatues, {
	Cardiovascularstatues_InsertParameters,
} from './cardiovascularstatues';
import Eliminationandexchange, {
	Eliminationandexchange_InsertParameters,
} from './eliminationandexchange';
import Healthpromotion, {
	Healthpromotion_InsertParameters,
} from './healthpromotion';
import Musculoskeletalstatus, {
	Musculoskeletalstatus_InsertParameters,
} from './musculoskeletalstatus';
import Nutrition, { Nutrition_InsertParameters } from './nutrition';
import Patient, { Patient_InsertParameters } from './patient';
import Perceptionandcognition, {
	Perceptionandcognition_InsertParameters,
} from './perceptionandcognition';
import Pulmonarystatus, {
	Pulmonarystatus_InsertParameters,
} from './pulmonarystatus';
import Rolesandrelationships, {
	Rolesandrelationships_InsertParameters,
} from './rolesandrelationships';
import Selfperception, {
	Selfperception_InsertParameters,
} from './selfperception';
import Sexualityfemale, {
	Sexualityfemale_InsertParameters,
} from './sexualityfemale';
import Sexualitymen, { Sexualitymen_InsertParameters } from './sexualitymen';
import Sleeppattern, { Sleeppattern_InsertParameters } from './sleeppattern';

interface DatabaseSchema {
	cardiovascularstatues: {
		record: Cardiovascularstatues;
		insert: Cardiovascularstatues_InsertParameters;
	};
	eliminationandexchange: {
		record: Eliminationandexchange;
		insert: Eliminationandexchange_InsertParameters;
	};
	healthpromotion: {
		record: Healthpromotion;
		insert: Healthpromotion_InsertParameters;
	};
	musculoskeletalstatus: {
		record: Musculoskeletalstatus;
		insert: Musculoskeletalstatus_InsertParameters;
	};
	nutrition: { record: Nutrition; insert: Nutrition_InsertParameters };
	patient: { record: Patient; insert: Patient_InsertParameters };
	perceptionandcognition: {
		record: Perceptionandcognition;
		insert: Perceptionandcognition_InsertParameters;
	};
	pulmonarystatus: {
		record: Pulmonarystatus;
		insert: Pulmonarystatus_InsertParameters;
	};
	rolesandrelationships: {
		record: Rolesandrelationships;
		insert: Rolesandrelationships_InsertParameters;
	};
	selfperception: {
		record: Selfperception;
		insert: Selfperception_InsertParameters;
	};
	sexualityfemale: {
		record: Sexualityfemale;
		insert: Sexualityfemale_InsertParameters;
	};
	sexualitymen: { record: Sexualitymen; insert: Sexualitymen_InsertParameters };
	sleeppattern: { record: Sleeppattern; insert: Sleeppattern_InsertParameters };
}
export default DatabaseSchema;

function serializeValue(
	_tableName: string,
	_columnName: string,
	value: unknown,
): unknown {
	return value;
}
export { serializeValue };
