/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gyD/YgQEkFHytIlsOo21q6T6TYMfGzicX/PeX4fO397N3nXkB5a5K5ipNTrBPAIHzlzB8LWc/FJF39xeb2b3Ig==
 */

// eslint:disable
// tslint:disable

interface Musculoskeletalstatus {
	haverequiredenergy: string | null;
	id: number;
	muscleatroph: string | null;
	muscleton: string | null;
	patient_id: number;
	rangeofmotion: string | null;
	rangeofmotiontobed: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	selfcareinbathing: string | null;
	selfcareindressing: string | null;
	selfcareinfeedin: string | null;
	selfcareinmovinginbed: string | null;
	selfcareintoileting: string | null;
	selfcareinwalking: string | null;
	usingofambulatoryaid: string | null;
	walking: string | null;
}
export default Musculoskeletalstatus;

interface Musculoskeletalstatus_InsertParameters {
	haverequiredenergy?: string | null;
	id: number;
	muscleatroph?: string | null;
	muscleton?: string | null;
	patient_id: number;
	rangeofmotion?: string | null;
	rangeofmotiontobed?: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	selfcareinbathing?: string | null;
	selfcareindressing?: string | null;
	selfcareinfeedin?: string | null;
	selfcareinmovinginbed?: string | null;
	selfcareintoileting?: string | null;
	selfcareinwalking?: string | null;
	usingofambulatoryaid?: string | null;
	walking?: string | null;
}
export type { Musculoskeletalstatus_InsertParameters };
