/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: e/8CHX2wfbGoN8/oEMVRO5ucpoSmlyoIARo7PISLYtrWUfiLiRhdZoZ1thA2am3dJut1jcds7i68lU41QfsUeA==
 */

// eslint:disable
// tslint:disable

interface Nutrition {
	appetitepattern: string | null;
	bmi: string | null;
	decreasedfoodintake: string | null;
	difficultyinchewing: string | null;
	examinationgums: string | null;
	height: string | null;
	id: number;
	looseweightinpastthreemonth: string | null;
	mouthcondition: string | null;
	needspecialcare: string | null;
	npo: string | null;
	patient_id: number;
	qualityofvomiting: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	skinturgor: string | null;
	vomiting: string | null;
	weight: string | null;
}
export default Nutrition;

interface Nutrition_InsertParameters {
	appetitepattern?: string | null;
	bmi?: string | null;
	decreasedfoodintake?: string | null;
	difficultyinchewing?: string | null;
	examinationgums?: string | null;
	height?: string | null;
	id: number;
	looseweightinpastthreemonth?: string | null;
	mouthcondition?: string | null;
	needspecialcare?: string | null;
	npo?: string | null;
	patient_id: number;
	qualityofvomiting?: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	skinturgor?: string | null;
	vomiting?: string | null;
	weight?: string | null;
}
export type { Nutrition_InsertParameters };
