/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: eGmD7G+MArdkwXAwLeVsqbr0nm+e9p6UyYiW60k+UVJz39pYMQoUdapJWevyWDaGW12ytvuSTeGZinnGE6aL7w==
 */

// eslint:disable
// tslint:disable

interface Perceptionandcognition {
	gcs: string | null;
	hearing: string | null;
	id: number;
	memoryimpairment: string | null;
	orientationto: string | null;
	patient_id: number;
	pupilssize: string | null;
	reactiverolightandaccommodation: string | null;
	reactivetolightandaccommodation: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	status: string | null;
	verbalcommunicationproblems: string | null;
	vision: string | null;
}
export default Perceptionandcognition;

interface Perceptionandcognition_InsertParameters {
	gcs?: string | null;
	hearing?: string | null;
	id: number;
	memoryimpairment?: string | null;
	orientationto?: string | null;
	patient_id: number;
	pupilssize?: string | null;
	reactiverolightandaccommodation?: string | null;
	reactivetolightandaccommodation?: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	status?: string | null;
	verbalcommunicationproblems?: string | null;
	vision?: string | null;
}
export type { Perceptionandcognition_InsertParameters };
