/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: MUBO8/j6GX2cM36XNkHYXVsy+79YePb4CV8t5FcO8MI4hF5z+MwH2f1Tx7Z9j3JtXRbe01zpVElxwX7POqLdXw==
 */

// eslint:disable
// tslint:disable

interface Pulmonarystatus {
	breathingpattern: string | null;
	cough: string | null;
	dyspnea: string | null;
	id: number;
	lungeauscultation: string | null;
	patient_id: number;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	respirationrate: string | null;
	spo2: string | null;
	sputum: string | null;
	sputumcharacteristic: string | null;
}
export default Pulmonarystatus;

interface Pulmonarystatus_InsertParameters {
	breathingpattern?: string | null;
	cough?: string | null;
	dyspnea?: string | null;
	id: number;
	lungeauscultation?: string | null;
	patient_id: number;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	respirationrate?: string | null;
	spo2?: string | null;
	sputum?: string | null;
	sputumcharacteristic?: string | null;
}
export type { Pulmonarystatus_InsertParameters };
