/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: UbvLYVo5WVzJMllQYjpqGNg3AP6KwTvJXfREevrRoQMfryIRamLhgFh9QyCAvStBkrh5v4zEnW2qtorURy70GQ==
 */

// eslint:disable
// tslint:disable

interface Rolesandrelationships {
	decreasedsocialinteraction: string | null;
	familycommunication: string | null;
	familydependentonpatient: string | null;
	familyincome: string | null;
	id: number;
	livealoneorwithfamily: string | null;
	patient_id: number;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	unknown: string | null;
}
export default Rolesandrelationships;

interface Rolesandrelationships_InsertParameters {
	decreasedsocialinteraction?: string | null;
	familycommunication?: string | null;
	familydependentonpatient?: string | null;
	familyincome?: string | null;
	id: number;
	livealoneorwithfamily?: string | null;
	patient_id: number;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	unknown?: string | null;
}
export type { Rolesandrelationships_InsertParameters };
