/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: PR38HgKhkoWMSjJqbLfUNv6ZfmEodvnjwA1g10W7NHxxh0posoyiWhHQVNzYBmU/V2Sm5NHB1p6YvkVSuAaHWg==
 */

// eslint:disable
// tslint:disable

interface Selfperception {
	bodychangedfeelings: string | null;
	everfeelyoulosehope: string | null;
	id: number;
	oftenmakethepatientangry: string | null;
	patient_id: number;
	patienthesitanttomakedecisions: string | null;
	patientoftenfeelgoodaboutself: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	skillstohandlenewsituations: string | null;
}
export default Selfperception;

interface Selfperception_InsertParameters {
	bodychangedfeelings?: string | null;
	everfeelyoulosehope?: string | null;
	id: number;
	oftenmakethepatientangry?: string | null;
	patient_id: number;
	patienthesitanttomakedecisions?: string | null;
	patientoftenfeelgoodaboutself?: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	skillstohandlenewsituations?: string | null;
}
export type { Selfperception_InsertParameters };
