/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: OUSA/fcEcRRpPurXciGs8wYZ/Ks+q/Crb51kyp7K7eZJgXglh/b9oXV6t2AgBqHw2Xki5QsK3dDWgQngALvsFg==
 */

// eslint:disable
// tslint:disable

interface Sexualitymen {
	effectofthediseaseonsexualperformance: string | null;
	historyofbloodygenitaldischarge: string | null;
	id: number;
	patient_id: number;
	prostatichyperplasia: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	sexuallytransmitteddiseases: string | null;
}
export default Sexualitymen;

interface Sexualitymen_InsertParameters {
	effectofthediseaseonsexualperformance?: string | null;
	historyofbloodygenitaldischarge?: string | null;
	id: number;
	patient_id: number;
	prostatichyperplasia?: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	sexuallytransmitteddiseases?: string | null;
}
export type { Sexualitymen_InsertParameters };
