/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: bmXjIIFAPvFA5DPHOVMGFSxaIOt2l7KosmaAym8vvyMT0njTn3b5+BPMlEK0sqV3uYrr96MhButJjfSo+X+WSA==
 */

// eslint:disable
// tslint:disable

interface Sleeppattern {
	id: number;
	patient_id: number;
	reasonofsleepdisorder: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date: Date | null;
	satisfiedhissleep: string | null;
	sleephours: string | null;
	sleeppattern: string | null;
}
export default Sleeppattern;

interface Sleeppattern_InsertParameters {
	id: number;
	patient_id: number;
	reasonofsleepdisorder?: string | null;
	/**
	 * @default CURRENT_TIMESTAMP
	 */
	reg_date?: Date | null;
	satisfiedhissleep?: string | null;
	sleephours?: string | null;
	sleeppattern?: string | null;
}
export type { Sleeppattern_InsertParameters };
