version: '2'

services:
  # mongo:
  #   image: mongo:latest
  #   volumes:
  #     - ./data:/data/db:Z
  #   ports:
  #     - 27017:27017
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
