version: '3'

services:
  # mongo:
  #   image: mongo:latest
  #   volumes:
  #     - ./data:/data/db:Z
  #   ports:
  #     - 27017:27017
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 1202212022AaAa
      PGDATA : /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data:Z
